name: Notion Webhook Trigger

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  webhook_trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger webhook
      run: |
        curl -X POST https://steed-notion-webhook.onrender.com/webhook -H "Content-Type: application/json" -d '{}'
